[supervisord]
nodaemon=true
logfile=/tmp/supervisord.log
pidfile=/tmp/supervisord.pid

[program:php-fpm]
command=php-fpm
autorestart=true
stdout_logfile=/tmp/php-fpm.log
stderr_logfile=/tmp/php-fpm.log

[program:nginx]
command=/usr/sbin/nginx -g 'daemon off;'
autorestart=true
stdout_logfile=/tmp/nginx.log
stderr_logfile=/tmp/nginx.log
